{% set name = "billingegroup" %}
{% set version = "2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    - python
  run:
    - python
    - numpy
    - scipy
    - matplotlib
    - seaborn
    - fabio
    - pims
    - pyyaml
    - pandas
    - jupyter
    - pyfai  # [not win]
    - fire
    - ipython
    - scikit-beam

test:
  imports:
    - numpy
    - scipy
    - matplotlib
    - seaborn
    - fabio
    - pims
    - yaml
    - pandas
    - jupyter
    - pyFAI  # [not win]
    - fire
    - skbeam

about:
  home: https://thebillingegroup.com/
  summary: 'Metapackage for the Billinge Group'

extra:
  recipe-maintainers:
    - CJ-Wright
    - chiahaoliu
    - sbanerjee23
    - sbillinge
