{% set name = "billingegroup" %}
{% set version = "3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

build:
  noarch: python
  number: 1

requirements:
  build:
    - python
  run:
    - python
    - numpy
    - scipy
    - matplotlib-base
    - seaborn
    - fabio
    - pims
    - pyyaml
    - pandas
    - jupyter
    - pyfai
    - fire
    - ipython
    - scikit-beam

test:
  imports:
    - numpy
    - scipy
    - matplotlib-base
    - seaborn
    - fabio
    - pims
    - yaml
    - pandas
    - jupyter
    - pyFAI
    - fire
    - skbeam

about:
  home: https://thebillingegroup.com/
  summary: 'Metapackage for the Billinge Group'
  license: NA

extra:
  recipe-maintainers:
    - CJ-Wright
    - chiahaoliu
    - sbanerjee23
    - sbillinge
