travis:
  secure:
    BINSTAR_TOKEN: Co+4osnV5mT4KVVN36InIQm3Nn30P54j7kl6kLuPvKSlUEGQhFp24JQaSc7GjDQrVCmM9SIJoIJbyjE81NEVpPZ3ACsd6kRbff2NzKoWnGra7HkRDdlGMEPlqjZyxOQn0zpHjKPDsYu5WPPweHESw5XA/effZkFMMsgu4eGt7ewCDeLzKbfrVhpBFuSuzmOvRUuc9D0x176f3LeY1xlB0/s5evX4cH3As8fRzpxntFaI9Yne7PINjHefzTX2cSEWjl5yAhzCaaN2FqUndDI7HJWWC1sU1iDWcNRjrfswGWYNUxQOnLmsTHa8Ltov6928MOQSoqBB0o6zgiYtVzJuAzFmZSFKf0uMTjZETT2DTwopFMaPHjEHSgDU/6C5VP9gfteGCgYOYH/ANKIWO24D2WoKdF21oEPtDdzkC45r3hEDYlei6sGBuLBHpJrDE77Wz2nCyiK839wFDBpKGQAQjs3zbMhIg3Uco8RpP33ifL00+3TpJYHl1y4RivOCZuE8ylLR/lwgtVpPLggFm9avVPa8GUtN30/wKofJr+0w4dFYMnag0ZNPyVdVojU6uOAcY4f3mh38F0ti/v+JZ7R71Bsb0jTgUoz5dmsogjgCc1xgWD3+srui83uaVqGJgWWsKOwir1B8e7JwteLAJehiaHNjncySH4iqh25YY2boG3U=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
